;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        conor-helm-kill-ring-regsters
        cua-copy-region
        cua-cut-region
        cua-exchange-point-and-mark
        cua-paste
        cua-paste-pop
        cycle-spacing
        downcase-region
        end-of-buffer
        end-of-visual-line
        ess-roxy-move-beginning-of-line
        forward-sexp
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        insert-register
        kill-region
        markdown-outdent-or-delete
        my/smarter-move-beginning-of-line
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        orgtbl-hijacker-command-109
        orgtbl-self-insert-command
        origami-backward-fold-same-level
        origami-forward-fold-same-level
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-join-sexp
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        sp-splice-sexp
        sp-up-sexp
        upcase-region
        wdired--self-insert
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ))
